name: gone_board
description: "A stylish and animated onboarding screen for your App. It's easy to use light weight and customizable."
version: 1.0.4
homepage: https://github.com/ratulhasanruhan/gone_board
repository: https://github.com/ratulhasanruhan/gone_board
issue_tracker: https://github.com/ratulhasanruhan/gone_board/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - ui
  - onboarding
  - animated
  - pageview


authors:
  - Ratul Hasan Ruhan



screenshots:
  - description: "Example of first page"
    path: example/screenshot/screenshot1.png
  - description: "Example of middle page"
    path: example/screenshot/screenshot2.png
  - description: "Example of final page"
    path: example/screenshot/screenshot3.png

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
